/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const SubjectAlternativeNames: msRest.CompositeMapper = {
  serializedName: "SubjectAlternativeNames",
  type: {
    name: "Composite",
    className: "SubjectAlternativeNames",
    modelProperties: {
      dnsNames: {
        serializedName: "dns_names",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      emails: {
        serializedName: "emails",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      upns: {
        serializedName: "upns",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const PropertyAttributes: msRest.CompositeMapper = {
  serializedName: "PropertyAttributes",
  type: {
    name: "Composite",
    className: "PropertyAttributes",
    modelProperties: {
      notBefore: {
        serializedName: "notBefore",
        type: {
          name: "DateTime"
        }
      },
      expires: {
        serializedName: "expires",
        type: {
          name: "DateTime"
        }
      },
      created: {
        serializedName: "created",
        type: {
          name: "DateTime"
        }
      },
      updated: {
        serializedName: "updated",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const PropertyVersion: msRest.CompositeMapper = {
  serializedName: "PropertyVersion",
  type: {
    name: "Composite",
    className: "PropertyVersion",
    modelProperties: {
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      attributes: {
        serializedName: "attributes",
        type: {
          name: "Composite",
          className: "PropertyAttributes"
        }
      }
    }
  }
};

export const Certificate: msRest.CompositeMapper = {
  serializedName: "Certificate",
  type: {
    name: "Composite",
    className: "Certificate",
    modelProperties: {
      issuer: {
        required: true,
        serializedName: "issuer",
        type: {
          name: "String"
        }
      },
      password: {
        serializedName: "password",
        type: {
          name: "String"
        }
      },
      subject: {
        serializedName: "subject",
        type: {
          name: "String"
        }
      },
      sans: {
        serializedName: "sans",
        type: {
          name: "Composite",
          className: "SubjectAlternativeNames"
        }
      },
      validityInMonths: {
        serializedName: "validityInMonths",
        type: {
          name: "Number"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "ByteArray"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      eTag: {
        serializedName: "eTag",
        type: {
          name: "String"
        }
      },
      selfUri: {
        readOnly: true,
        serializedName: "selfUri",
        type: {
          name: "String"
        }
      },
      selectors: {
        serializedName: "selectors",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      attributes: {
        serializedName: "attributes",
        type: {
          name: "Composite",
          className: "PropertyAttributes"
        }
      },
      versions: {
        serializedName: "versions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "PropertyVersion"
            }
          }
        }
      },
      baseUri: {
        serializedName: "baseUri",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const JsonWebKey: msRest.CompositeMapper = {
  serializedName: "JsonWebKey",
  type: {
    name: "Composite",
    className: "JsonWebKey",
    modelProperties: {
      kid: {
        serializedName: "kid",
        type: {
          name: "String"
        }
      },
      kty: {
        required: true,
        serializedName: "kty",
        type: {
          name: "String"
        }
      },
      keyOps: {
        serializedName: "key_ops",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      n: {
        serializedName: "n",
        type: {
          name: "ByteArray"
        }
      },
      e: {
        serializedName: "e",
        type: {
          name: "ByteArray"
        }
      },
      dp: {
        serializedName: "dp",
        type: {
          name: "ByteArray"
        }
      },
      dq: {
        serializedName: "dq",
        type: {
          name: "ByteArray"
        }
      },
      qi: {
        serializedName: "qi",
        type: {
          name: "ByteArray"
        }
      },
      p: {
        serializedName: "p",
        type: {
          name: "ByteArray"
        }
      },
      q: {
        serializedName: "q",
        type: {
          name: "ByteArray"
        }
      },
      crv: {
        serializedName: "crv",
        type: {
          name: "ByteArray"
        }
      },
      x: {
        serializedName: "x",
        type: {
          name: "ByteArray"
        }
      },
      y: {
        serializedName: "y",
        type: {
          name: "ByteArray"
        }
      },
      d: {
        serializedName: "d",
        type: {
          name: "ByteArray"
        }
      },
      k: {
        serializedName: "k",
        type: {
          name: "ByteArray"
        }
      },
      keyHsm: {
        serializedName: "key_hsm",
        type: {
          name: "ByteArray"
        }
      }
    },
    additionalProperties: {
      type: {
        name: "Object"
      }
    }
  }
};

export const EncryptionKey: msRest.CompositeMapper = {
  serializedName: "EncryptionKey",
  type: {
    name: "Composite",
    className: "EncryptionKey",
    modelProperties: {
      keySize: {
        serializedName: "keySize",
        type: {
          name: "Number"
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "Composite",
          className: "JsonWebKey",
          additionalProperties: {
            type: {
              name: "Object"
            }
          }
        }
      },
      eTag: {
        serializedName: "eTag",
        type: {
          name: "String"
        }
      },
      selfUri: {
        readOnly: true,
        serializedName: "selfUri",
        type: {
          name: "String"
        }
      },
      selectors: {
        serializedName: "selectors",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      attributes: {
        serializedName: "attributes",
        type: {
          name: "Composite",
          className: "PropertyAttributes"
        }
      },
      versions: {
        serializedName: "versions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "PropertyVersion"
            }
          }
        }
      },
      baseUri: {
        serializedName: "baseUri",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Property: msRest.CompositeMapper = {
  serializedName: "Property",
  type: {
    name: "Composite",
    className: "Property",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      contentType: {
        serializedName: "contentType",
        type: {
          name: "String"
        }
      },
      eTag: {
        serializedName: "eTag",
        type: {
          name: "String"
        }
      },
      selfUri: {
        readOnly: true,
        serializedName: "selfUri",
        type: {
          name: "String"
        }
      },
      selectors: {
        serializedName: "selectors",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      attributes: {
        serializedName: "attributes",
        type: {
          name: "Composite",
          className: "PropertyAttributes"
        }
      },
      baseUri: {
        serializedName: "baseUri",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Secret: msRest.CompositeMapper = {
  serializedName: "Secret",
  type: {
    name: "Composite",
    className: "Secret",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      contentType: {
        serializedName: "contentType",
        type: {
          name: "String"
        }
      },
      eTag: {
        serializedName: "eTag",
        type: {
          name: "String"
        }
      },
      selfUri: {
        readOnly: true,
        serializedName: "selfUri",
        type: {
          name: "String"
        }
      },
      selectors: {
        serializedName: "selectors",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      attributes: {
        serializedName: "attributes",
        type: {
          name: "Composite",
          className: "PropertyAttributes"
        }
      },
      versions: {
        serializedName: "versions",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "PropertyVersion"
            }
          }
        }
      },
      baseUri: {
        serializedName: "baseUri",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ValidationResult: msRest.CompositeMapper = {
  serializedName: "ValidationResult",
  type: {
    name: "Composite",
    className: "ValidationResult",
    modelProperties: {
      errors: {
        readOnly: true,
        serializedName: "errors",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "String"
                }
              }
            }
          }
        }
      },
      isValid: {
        readOnly: true,
        serializedName: "isValid",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const DecryptOperation: msRest.CompositeMapper = {
  serializedName: "DecryptOperation",
  type: {
    name: "Composite",
    className: "DecryptOperation",
    modelProperties: {
      algorithm: {
        required: true,
        serializedName: "algorithm",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "ByteArray"
        }
      }
    }
  }
};

export const EncryptOperation: msRest.CompositeMapper = {
  serializedName: "EncryptOperation",
  type: {
    name: "Composite",
    className: "EncryptOperation",
    modelProperties: {
      algorithm: {
        required: true,
        serializedName: "algorithm",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "ByteArray"
        }
      }
    }
  }
};

export const SignOperation: msRest.CompositeMapper = {
  serializedName: "SignOperation",
  type: {
    name: "Composite",
    className: "SignOperation",
    modelProperties: {
      algorithm: {
        required: true,
        serializedName: "algorithm",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "ByteArray"
        }
      }
    }
  }
};

export const UnwrapKeyOperation: msRest.CompositeMapper = {
  serializedName: "UnwrapKeyOperation",
  type: {
    name: "Composite",
    className: "UnwrapKeyOperation",
    modelProperties: {
      algorithm: {
        required: true,
        serializedName: "algorithm",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "ByteArray"
        }
      }
    }
  }
};

export const VerifyOperation: msRest.CompositeMapper = {
  serializedName: "VerifyOperation",
  type: {
    name: "Composite",
    className: "VerifyOperation",
    modelProperties: {
      algorithm: {
        required: true,
        serializedName: "algorithm",
        type: {
          name: "String"
        }
      },
      digest: {
        required: true,
        serializedName: "digest",
        type: {
          name: "ByteArray"
        }
      },
      signature: {
        required: true,
        serializedName: "signature",
        type: {
          name: "ByteArray"
        }
      }
    }
  }
};

export const WrapKeyOperation: msRest.CompositeMapper = {
  serializedName: "WrapKeyOperation",
  type: {
    name: "Composite",
    className: "WrapKeyOperation",
    modelProperties: {
      algorithm: {
        required: true,
        serializedName: "algorithm",
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "ByteArray"
        }
      }
    }
  }
};

export const ApiResponseString: msRest.CompositeMapper = {
  serializedName: "ApiResponse_String_",
  type: {
    name: "Composite",
    className: "ApiResponseString",
    modelProperties: {
      errors: {
        readOnly: true,
        serializedName: "errors",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "String"
                }
              }
            }
          }
        }
      },
      isValid: {
        readOnly: true,
        serializedName: "isValid",
        type: {
          name: "Boolean"
        }
      },
      requestId: {
        readOnly: true,
        serializedName: "requestId",
        type: {
          name: "String"
        }
      },
      result: {
        readOnly: true,
        serializedName: "result",
        type: {
          name: "String"
        }
      },
      statusCode: {
        readOnly: true,
        serializedName: "statusCode",
        type: {
          name: "Number"
        }
      }
    }
  }
};
