/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const id: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "Id",
    type: {
      name: "Uuid"
    }
  }
};
export const name: msRest.OperationURLParameter = {
  parameterPath: "name",
  skipEncoding: true,
  mapper: {
    required: true,
    serializedName: "Name",
    type: {
      name: "String"
    }
  }
};
export const selectorFilterType: msRest.OperationQueryParameter = {
  parameterPath: "selectorFilterType",
  mapper: {
    required: true,
    serializedName: "SelectorFilterType",
    type: {
      name: "Number"
    }
  }
};
export const selectors: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "selectors"
  ],
  mapper: {
    serializedName: "Selectors",
    type: {
      name: "String"
    }
  }
};
export const version: msRest.OperationURLParameter = {
  parameterPath: "version",
  mapper: {
    required: true,
    serializedName: "Version",
    type: {
      name: "String"
    }
  }
};
