/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/encryptionKeyOperationsMappers";
import * as Parameters from "../models/parameters";
import { HCHBServicesPropertyServiceAPIv1Context } from "../hCHBServicesPropertyServiceAPIv1Context";

/** Class representing a EncryptionKeyOperations. */
export class EncryptionKeyOperations {
  private readonly client: HCHBServicesPropertyServiceAPIv1Context;

  /**
   * Create a EncryptionKeyOperations.
   * @param {HCHBServicesPropertyServiceAPIv1Context} client Reference to the service client.
   */
  constructor(client: HCHBServicesPropertyServiceAPIv1Context) {
    this.client = client;
  }

  /**
   * @param name
   * @param id
   * @param algorithm
   * @param value
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsEncryptResponse>
   */
  encrypt(name: string, id: string, algorithm: number, value: Uint8Array, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsEncryptResponse>;
  /**
   * @param name
   * @param id
   * @param algorithm
   * @param value
   * @param callback The callback
   */
  encrypt(name: string, id: string, algorithm: number, value: Uint8Array, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param name
   * @param id
   * @param algorithm
   * @param value
   * @param options The optional parameters
   * @param callback The callback
   */
  encrypt(name: string, id: string, algorithm: number, value: Uint8Array, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  encrypt(name: string, id: string, algorithm: number, value: Uint8Array, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsEncryptResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        id,
        algorithm,
        value,
        options
      },
      encryptOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsEncryptResponse>;
  }

  /**
   * @param name
   * @param id
   * @param algorithm
   * @param value
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsDecryptResponse>
   */
  decrypt(name: string, id: string, algorithm: number, value: Uint8Array, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsDecryptResponse>;
  /**
   * @param name
   * @param id
   * @param algorithm
   * @param value
   * @param callback The callback
   */
  decrypt(name: string, id: string, algorithm: number, value: Uint8Array, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param name
   * @param id
   * @param algorithm
   * @param value
   * @param options The optional parameters
   * @param callback The callback
   */
  decrypt(name: string, id: string, algorithm: number, value: Uint8Array, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  decrypt(name: string, id: string, algorithm: number, value: Uint8Array, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsDecryptResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        id,
        algorithm,
        value,
        options
      },
      decryptOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsDecryptResponse>;
  }

  /**
   * @param property
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsUpdateResponse>
   */
  update(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsUpdateResponse>;
  /**
   * @param property
   * @param callback The callback
   */
  update(property: Models.EncryptionKey, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param property
   * @param options The optional parameters
   * @param callback The callback
   */
  update(property: Models.EncryptionKey, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  update(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        property,
        options
      },
      updateOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsUpdateResponse>;
  }

  /**
   * @param property
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsCreateResponse>
   */
  create(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsCreateResponse>;
  /**
   * @param property
   * @param callback The callback
   */
  create(property: Models.EncryptionKey, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param property
   * @param options The optional parameters
   * @param callback The callback
   */
  create(property: Models.EncryptionKey, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  create(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsCreateResponse> {
    return this.client.sendOperationRequest(
      {
        property,
        options
      },
      createOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsCreateResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsReadResponse>
   */
  read(version: string, id: string, name: string, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsReadResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param callback The callback
   */
  read(version: string, id: string, name: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param options The optional parameters
   * @param callback The callback
   */
  read(version: string, id: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  read(version: string, id: string, name: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsReadResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        options
      },
      readOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsReadResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsDeleteMethodResponse>
   */
  deleteMethod(version: string, id: string, name: string, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsDeleteMethodResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param callback The callback
   */
  deleteMethod(version: string, id: string, name: string, callback: msRest.ServiceCallback<string>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(version: string, id: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<string>): void;
  deleteMethod(version: string, id: string, name: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<string>, callback?: msRest.ServiceCallback<string>): Promise<Models.EncryptionKeyOperationsDeleteMethodResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        options
      },
      deleteMethodOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsDeleteMethodResponse>;
  }

  /**
   * @param selectorFilterType
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsSearchResponse>
   */
  search(selectorFilterType: number, options?: Models.EncryptionKeyOperationsSearchOptionalParams): Promise<Models.EncryptionKeyOperationsSearchResponse>;
  /**
   * @param selectorFilterType
   * @param callback The callback
   */
  search(selectorFilterType: number, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param selectorFilterType
   * @param options The optional parameters
   * @param callback The callback
   */
  search(selectorFilterType: number, options: Models.EncryptionKeyOperationsSearchOptionalParams, callback: msRest.ServiceCallback<any>): void;
  search(selectorFilterType: number, options?: Models.EncryptionKeyOperationsSearchOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsSearchResponse> {
    return this.client.sendOperationRequest(
      {
        selectorFilterType,
        options
      },
      searchOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsSearchResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const encryptOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/{name}/{id}/Encrypt",
  urlParameters: [
    Parameters.name2,
    Parameters.id1
  ],
  queryParameters: [
    Parameters.algorithm
  ],
  requestBody: {
    parameterPath: "value",
    mapper: {
      required: true,
      serializedName: "value",
      type: {
        name: "ByteArray"
      }
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "ByteArray"
        }
      }
    },
    400: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    401: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    404: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};

const decryptOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/{name}/{id}/Decrypt",
  urlParameters: [
    Parameters.name2,
    Parameters.id1
  ],
  queryParameters: [
    Parameters.algorithm
  ],
  requestBody: {
    parameterPath: "value",
    mapper: {
      required: true,
      serializedName: "value",
      type: {
        name: "ByteArray"
      }
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "ByteArray"
        }
      }
    },
    400: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    401: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    404: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};

const updateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "api/v1/EncryptionKeys",
  requestBody: {
    parameterPath: "property",
    mapper: {
      ...Mappers.EncryptionKey,
      required: true
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: Mappers.EncryptionKey
    },
    400: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    401: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    404: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    409: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};

const createOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys",
  requestBody: {
    parameterPath: "property",
    mapper: {
      ...Mappers.EncryptionKey,
      required: true
    }
  },
  contentType: "application/json-patch+json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: Mappers.EncryptionKey
    },
    400: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    401: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};

const readOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/v1/EncryptionKeys/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id0,
    Parameters.name0
  ],
  responses: {
    200: {
      bodyMapper: Mappers.EncryptionKey
    },
    400: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    401: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    404: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "api/v1/EncryptionKeys/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id0,
    Parameters.name0
  ],
  responses: {
    200: {},
    400: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    401: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    404: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};

const searchOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/v1/EncryptionKeys/Search",
  queryParameters: [
    Parameters.name1,
    Parameters.selectorFilterType,
    Parameters.selectors
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "EncryptionKey"
            }
          }
        }
      }
    },
    400: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    401: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    404: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "String"
        }
      }
    },
    default: {}
  },
  serializer
};
