/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/encryptionKeyOperationsMappers";
import * as Parameters from "../models/parameters";
import { HCHBServicesPropertyServiceAPIv1Context } from "../hCHBServicesPropertyServiceAPIv1Context";

/** Class representing a EncryptionKeyOperations. */
export class EncryptionKeyOperations {
  private readonly client: HCHBServicesPropertyServiceAPIv1Context;

  /**
   * Create a EncryptionKeyOperations.
   * @param {HCHBServicesPropertyServiceAPIv1Context} client Reference to the service client.
   */
  constructor(client: HCHBServicesPropertyServiceAPIv1Context) {
    this.client = client;
  }

  /**
   * @param property
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsUpdateResponse>
   */
  update(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsUpdateResponse>;
  /**
   * @param property
   * @param callback The callback
   */
  update(property: Models.EncryptionKey, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param property
   * @param options The optional parameters
   * @param callback The callback
   */
  update(property: Models.EncryptionKey, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  update(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        property,
        options
      },
      updateOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsUpdateResponse>;
  }

  /**
   * @param property
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsCreateResponse>
   */
  create(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsCreateResponse>;
  /**
   * @param property
   * @param callback The callback
   */
  create(property: Models.EncryptionKey, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param property
   * @param options The optional parameters
   * @param callback The callback
   */
  create(property: Models.EncryptionKey, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  create(property: Models.EncryptionKey, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsCreateResponse> {
    return this.client.sendOperationRequest(
      {
        property,
        options
      },
      createOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsCreateResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsDecryptResponse>
   */
  decrypt(version: string, id: string, name: string, operation: Models.DecryptOperation, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsDecryptResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param callback The callback
   */
  decrypt(version: string, id: string, name: string, operation: Models.DecryptOperation, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param options The optional parameters
   * @param callback The callback
   */
  decrypt(version: string, id: string, name: string, operation: Models.DecryptOperation, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  decrypt(version: string, id: string, name: string, operation: Models.DecryptOperation, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsDecryptResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        operation,
        options
      },
      decryptOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsDecryptResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsReadResponse>
   */
  read(version: string, id: string, name: string, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsReadResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param callback The callback
   */
  read(version: string, id: string, name: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param options The optional parameters
   * @param callback The callback
   */
  read(version: string, id: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  read(version: string, id: string, name: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsReadResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        options
      },
      readOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsReadResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsDeleteMethodResponse>
   */
  deleteMethod(version: string, id: string, name: string, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsDeleteMethodResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param callback The callback
   */
  deleteMethod(version: string, id: string, name: string, callback: msRest.ServiceCallback<Models.ValidationResult>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(version: string, id: string, name: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ValidationResult>): void;
  deleteMethod(version: string, id: string, name: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ValidationResult>, callback?: msRest.ServiceCallback<Models.ValidationResult>): Promise<Models.EncryptionKeyOperationsDeleteMethodResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        options
      },
      deleteMethodOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsDeleteMethodResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsEncryptResponse>
   */
  encrypt(version: string, id: string, name: string, operation: Models.EncryptOperation, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsEncryptResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param callback The callback
   */
  encrypt(version: string, id: string, name: string, operation: Models.EncryptOperation, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param options The optional parameters
   * @param callback The callback
   */
  encrypt(version: string, id: string, name: string, operation: Models.EncryptOperation, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  encrypt(version: string, id: string, name: string, operation: Models.EncryptOperation, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsEncryptResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        operation,
        options
      },
      encryptOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsEncryptResponse>;
  }

  /**
   * @param name
   * @param selectorFilterType
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsSearchResponse>
   */
  search(name: string, selectorFilterType: number, options?: Models.EncryptionKeyOperationsSearchOptionalParams): Promise<Models.EncryptionKeyOperationsSearchResponse>;
  /**
   * @param name
   * @param selectorFilterType
   * @param callback The callback
   */
  search(name: string, selectorFilterType: number, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param name
   * @param selectorFilterType
   * @param options The optional parameters
   * @param callback The callback
   */
  search(name: string, selectorFilterType: number, options: Models.EncryptionKeyOperationsSearchOptionalParams, callback: msRest.ServiceCallback<any>): void;
  search(name: string, selectorFilterType: number, options?: Models.EncryptionKeyOperationsSearchOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsSearchResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        selectorFilterType,
        options
      },
      searchOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsSearchResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsSignResponse>
   */
  sign(version: string, id: string, name: string, operation: Models.SignOperation, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsSignResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param callback The callback
   */
  sign(version: string, id: string, name: string, operation: Models.SignOperation, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param options The optional parameters
   * @param callback The callback
   */
  sign(version: string, id: string, name: string, operation: Models.SignOperation, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  sign(version: string, id: string, name: string, operation: Models.SignOperation, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsSignResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        operation,
        options
      },
      signOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsSignResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsUnwrapKeyResponse>
   */
  unwrapKey(version: string, id: string, name: string, operation: Models.UnwrapKeyOperation, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsUnwrapKeyResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param callback The callback
   */
  unwrapKey(version: string, id: string, name: string, operation: Models.UnwrapKeyOperation, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param options The optional parameters
   * @param callback The callback
   */
  unwrapKey(version: string, id: string, name: string, operation: Models.UnwrapKeyOperation, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  unwrapKey(version: string, id: string, name: string, operation: Models.UnwrapKeyOperation, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsUnwrapKeyResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        operation,
        options
      },
      unwrapKeyOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsUnwrapKeyResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsVerifyResponse>
   */
  verify(version: string, id: string, name: string, operation: Models.VerifyOperation, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsVerifyResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param callback The callback
   */
  verify(version: string, id: string, name: string, operation: Models.VerifyOperation, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param options The optional parameters
   * @param callback The callback
   */
  verify(version: string, id: string, name: string, operation: Models.VerifyOperation, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  verify(version: string, id: string, name: string, operation: Models.VerifyOperation, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsVerifyResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        operation,
        options
      },
      verifyOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsVerifyResponse>;
  }

  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param [options] The optional parameters
   * @returns Promise<Models.EncryptionKeyOperationsWrapKeyResponse>
   */
  wrapKey(version: string, id: string, name: string, operation: Models.WrapKeyOperation, options?: msRest.RequestOptionsBase): Promise<Models.EncryptionKeyOperationsWrapKeyResponse>;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param callback The callback
   */
  wrapKey(version: string, id: string, name: string, operation: Models.WrapKeyOperation, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param version
   * @param id
   * @param name
   * @param operation
   * @param options The optional parameters
   * @param callback The callback
   */
  wrapKey(version: string, id: string, name: string, operation: Models.WrapKeyOperation, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  wrapKey(version: string, id: string, name: string, operation: Models.WrapKeyOperation, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EncryptionKeyOperationsWrapKeyResponse> {
    return this.client.sendOperationRequest(
      {
        version,
        id,
        name,
        operation,
        options
      },
      wrapKeyOperationSpec,
      callback) as Promise<Models.EncryptionKeyOperationsWrapKeyResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const updateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "api/v1/EncryptionKeys",
  requestBody: {
    parameterPath: "property",
    mapper: {
      ...Mappers.EncryptionKey,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.EncryptionKey
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    409: {
      bodyMapper: Mappers.ValidationResult
    },
    default: {}
  },
  serializer
};

const createOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys",
  requestBody: {
    parameterPath: "property",
    mapper: {
      ...Mappers.EncryptionKey,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.EncryptionKey
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    409: {
      bodyMapper: Mappers.ValidationResult
    },
    default: {}
  },
  serializer
};

const decryptOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/Decrypt/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  requestBody: {
    parameterPath: "operation",
    mapper: {
      ...Mappers.DecryptOperation,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "ByteArray"
        }
      }
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const readOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/v1/EncryptionKeys/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  contentType: "application/json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: Mappers.EncryptionKey
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "api/v1/EncryptionKeys/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  contentType: "application/json; charset=utf-8",
  responses: {
    200: {},
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const encryptOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/Encrypt/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  requestBody: {
    parameterPath: "operation",
    mapper: {
      ...Mappers.EncryptOperation,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "ByteArray"
        }
      }
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const searchOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/v1/EncryptionKeys/Search",
  queryParameters: [
    Parameters.name,
    Parameters.selectorFilterType,
    Parameters.selectors
  ],
  contentType: "application/json; charset=utf-8",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "EncryptionKey"
            }
          }
        }
      }
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const signOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/Sign/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  requestBody: {
    parameterPath: "operation",
    mapper: {
      ...Mappers.SignOperation,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "ByteArray"
        }
      }
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const unwrapKeyOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/UnwrapKey/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  requestBody: {
    parameterPath: "operation",
    mapper: {
      ...Mappers.UnwrapKeyOperation,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "ByteArray"
        }
      }
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const verifyOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/Verify/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  requestBody: {
    parameterPath: "operation",
    mapper: {
      ...Mappers.VerifyOperation,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Boolean"
        }
      }
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};

const wrapKeyOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/EncryptionKeys/WrapKey/{Name}/{Id}/{Version}",
  urlParameters: [
    Parameters.version,
    Parameters.id,
    Parameters.name
  ],
  requestBody: {
    parameterPath: "operation",
    mapper: {
      ...Mappers.WrapKeyOperation,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "ByteArray"
        }
      }
    },
    400: {
      bodyMapper: Mappers.ValidationResult
    },
    401: {},
    404: {},
    default: {}
  },
  serializer
};
