/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing PropertyAttributes.
 */
export interface PropertyAttributes {
  enabled?: boolean;
  notBefore?: Date;
  expires?: Date;
  created?: Date;
  updated?: Date;
}

/**
 * An interface representing PropertyVersion.
 */
export interface PropertyVersion {
  version?: string;
  attributes?: PropertyAttributes;
}

/**
 * An interface representing Certificate.
 */
export interface Certificate {
  id?: string;
  name: string;
  version?: string;
  value?: any;
  contentType?: string;
  eTag?: string;
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly selfUri?: string;
  selectors?: { [propertyName: string]: string };
  attributes?: PropertyAttributes;
  versions?: PropertyVersion[];
  baseUri?: string;
}

/**
 * An interface representing EncryptionKeyValue.
 */
export interface EncryptionKeyValue {
  n?: Uint8Array;
  e?: Uint8Array;
  dp?: Uint8Array;
  dq?: Uint8Array;
  qi?: Uint8Array;
  p?: Uint8Array;
  q?: Uint8Array;
  x?: Uint8Array;
  y?: Uint8Array;
  d?: Uint8Array;
  k?: Uint8Array;
  keyHsm?: Uint8Array;
}

/**
 * An interface representing EncryptionKey.
 */
export interface EncryptionKey {
  keyType?: number;
  keySize?: number;
  keyOperations?: number;
  ellipticCurveType?: number;
  id?: string;
  name: string;
  version?: string;
  value?: EncryptionKeyValue;
  contentType?: string;
  eTag?: string;
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly selfUri?: string;
  selectors?: { [propertyName: string]: string };
  attributes?: PropertyAttributes;
  versions?: PropertyVersion[];
  baseUri?: string;
}

/**
 * An interface representing ApiResponseString.
 */
export interface ApiResponseString {
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly errors?: { [propertyName: string]: string[] };
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly isValid?: boolean;
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly requestId?: string;
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly result?: string;
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly statusCode?: number;
}

/**
 * An interface representing Property.
 */
export interface Property {
  id?: string;
  name: string;
  value?: string;
  contentType?: string;
  eTag?: string;
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly selfUri?: string;
  selectors?: { [propertyName: string]: string };
  attributes: PropertyAttributes;
  baseUri?: string;
}

/**
 * An interface representing Secret.
 */
export interface Secret {
  id?: string;
  name: string;
  version?: string;
  value?: string;
  contentType?: string;
  eTag?: string;
  /**
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly selfUri?: string;
  selectors?: { [propertyName: string]: string };
  attributes: PropertyAttributes;
  versions?: PropertyVersion[];
  baseUri?: string;
}

/**
 * An interface representing HCHBServicesPropertyServiceAPIv1Options.
 */
export interface HCHBServicesPropertyServiceAPIv1Options extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface CertificateOperationsSearchOptionalParams extends msRest.RequestOptionsBase {
  name?: string;
  selectors?: string;
}

/**
 * Optional Parameters.
 */
export interface EncryptionKeyOperationsSearchOptionalParams extends msRest.RequestOptionsBase {
  name?: string;
  selectors?: string;
}

/**
 * Optional Parameters.
 */
export interface PropertyOperationsSearchOptionalParams extends msRest.RequestOptionsBase {
  name?: string;
  selectors?: string;
}

/**
 * Optional Parameters.
 */
export interface SecretOperationsSearchOptionalParams extends msRest.RequestOptionsBase {
  name?: string;
  selectors?: string;
}

/**
 * Contains response data for the update operation.
 */
export type CertificateOperationsUpdateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the create operation.
 */
export type CertificateOperationsCreateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the read operation.
 */
export type CertificateOperationsReadResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the deleteMethod operation.
 */
export type CertificateOperationsDeleteMethodResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: string;
  };
};

/**
 * Contains response data for the search operation.
 */
export type CertificateOperationsSearchResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the encrypt operation.
 */
export type EncryptionKeyOperationsEncryptResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the decrypt operation.
 */
export type EncryptionKeyOperationsDecryptResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the update operation.
 */
export type EncryptionKeyOperationsUpdateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the create operation.
 */
export type EncryptionKeyOperationsCreateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the read operation.
 */
export type EncryptionKeyOperationsReadResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the deleteMethod operation.
 */
export type EncryptionKeyOperationsDeleteMethodResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: string;
  };
};

/**
 * Contains response data for the search operation.
 */
export type EncryptionKeyOperationsSearchResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the ping operation.
 */
export type PingOperationsPingResponse = {
  /**
   * The parsed response body.
   */
  body: boolean;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: boolean;
  };
};

/**
 * Contains response data for the pingUser operation.
 */
export type PingOperationsPingUserResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: string;
  };
};

/**
 * Contains response data for the pingUserWrapped operation.
 */
export type PingOperationsPingUserWrappedResponse = ApiResponseString & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: ApiResponseString;
  };
};

/**
 * Contains response data for the update operation.
 */
export type PropertyOperationsUpdateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the create operation.
 */
export type PropertyOperationsCreateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the read operation.
 */
export type PropertyOperationsReadResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the deleteMethod operation.
 */
export type PropertyOperationsDeleteMethodResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: string;
  };
};

/**
 * Contains response data for the search operation.
 */
export type PropertyOperationsSearchResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the update operation.
 */
export type SecretOperationsUpdateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the create operation.
 */
export type SecretOperationsCreateResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the read operation.
 */
export type SecretOperationsReadResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};

/**
 * Contains response data for the deleteMethod operation.
 */
export type SecretOperationsDeleteMethodResponse = {
  /**
   * The parsed response body.
   */
  body: string;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: string;
  };
};

/**
 * Contains response data for the search operation.
 */
export type SecretOperationsSearchResponse = {
  /**
   * The parsed response body.
   */
  body: any;

  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
    /**
     * The response body as text (string format)
     */
    bodyAsText: string;

    /**
     * The response body as parsed JSON or XML
     */
    parsedBody: any;
  };
};
